version: "3.7"
services:
  vproapp:
    build:
      context: ./Docker-files/app
    image: aaleem1993/vproapp
    container_name: vproapp
    ports: 
      - "8080:8080"

  vprodb:
    build:
      context: ./Docker-files/db
    image: aaleem1993/vprodb
    container_name: vprodb 
    ports: 
      - "3306:3306"
    volumes:
      - myvolumedb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="vprodbpass"
      - MYSQL_DATABASE="accounts"

  vproweb:
    build:
      context: ./Docker-files/web
    image: aaleem1993/vproweb
    container_name: vproweb
    ports: 
      - "80:80"

  vprocache01:
    image: memcached 
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - rabbitmq.username=guest
      - rabbitmq.password=guest

volumes:
  myvolumedb: {}
